# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the release branch
on:
  push:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Helps set up MSBuild into PATH for later usage
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      #with:
        # Folder location of where vswhere.exe is located if a self-hosted agent
        #vswhere-path: # optional
        # Version of Visual Studio to search; defaults to latest if not specified
        #vs-version: # optional

    # Uses VSWhere.exe to locate latest MSBuild & put it into the PATH
    #- name: Setup MSBuild.exe
    #  uses: warrenbuckley/Setup-MSBuild@v1

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: msbuild test/test.sln -p:OutDir="out/"
      shell: cmd
